function [b Hd] = filtro_passa_bandas_4khz
%FILTRO_PASSA_BANDAS_4KHZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 06-Dec-2014 14:54:04

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 400;  % Sampling Frequency

Fstop1 = 15;              % First Stopband Frequency
Fpass1 = 16;              % First Passband Frequency
Fpass2 = 24;              % Second Passband Frequency
Fstop2 = 25;              % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.0001;          % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
