function b = filtro_passa_baixas_fc4k
%FILTRO_IIR_FC4K Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.3 and the Signal Processing Toolbox 6.21.
% Generated on: 06-Dec-2014 03:56:43

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in kHz.
Fs = 400;  % Sampling Frequency

Fpass = .4;               % Passband Frequency
Fstop = 6;               % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
